#!/usr/bin/env python3

from __future__ import annotations

import ast
import pathlib
import re
import textwrap
import collections.abc
from string import Formatter
from typing import Final

"""
Provides Python access to SQLite queries in a separate file or string

this should end up in the rst doc inseat of here

from file, text, import, resource


-- python:

   everything in following /* */ (on lines by themselves is copied verbatim).
   use to introduce types like :code:`from my mymod import mytype`


-- name:

    names query, -- comments become docstring, everything up to EOF or next -- name: / python:

"""


class _ChainMapRO:
    "Internal read-only chainmap for execute bindings"

    def __init__(self):
        self.maps = []

    def __getitem__(self, key: Any) -> Any:
        for map in self.maps:
            try:
                return map[key]
            except KeyError:
                pass
        raise KeyError(str(key))

    def items(self):
        seen = set()
        for map in self.maps:
            for k, v in map.items():
                if k not in seen:
                    seen.add(k)
                    yield (k, v)


# _ChainMapRO doesn't implement the full abc such as iter and len but
# they aren't used so we don't care!
collections.abc.Mapping.register(_ChainMapRO)


class NotSetType:
    __slots__ = ()

    def __repr__(self) -> str:
        return "NotSet"


NotSet: Final = NotSetType()
"Used to indicate a parameter value was not supplied, so locals can be used instead"

# only need the parse method
_template_parse = Formatter().parse


def _is_template_string(string: str) -> bool:
    "Checks if it is f-string style using {}, colons etc"
    print(f"{string=!r}")
    for literal, field, spec, conversion in _template_parse(string):
        if field is not None or spec is not None or conversion is not None:
            return True
    return False


def template_expand(template: str, vars: _ChainMapRO) -> str:
    res: list[str] = []
    bindings = {}

    def add_binding(v: Any):
        name = f"_id_{id(v)}"
        res.append(f"${name}")
        bindings[name] = v

    for literal, field, spec, conversion in _template_parse(template):
        if literal:
            res.append(literal)
        if field is None:
            continue
        match conversion:
            case None:
                conv = lambda x: x
            case "r":
                conv = repr
            case "s":
                conv = str
            case "a":
                conv = ascii
            case _:
                raise ValueError(f"Unknown {conversion=}")
        if not spec:
            add_binding(conv(vars[field]))
        else:
            spec = set(spec.split(":"))

            if "eval" in spec:
                spec.remove("eval")
                # ::TODO:: does this need __builtins__ for middle param so
                # eg len() works
                value = eval(field, None, vars)
            else:
                value = vars[field]

            if spec == {"id"}:
                value = conv(value)
                res.append('"' + value.replace('"', '""') + '"')
            elif spec == {"seq", "id"}:
                for i, v in enumerate(values):
                    if i:
                        res.append(", ")
                    res.append('"' + conv(value).replace('"', '""') + '"')
            elif spec == {"seq"}:
                for i, v in enumerate(values):
                    if i:
                        res.append(", ")
                    add_binding(conv(v))
            else:
                raise ValueError(f"Unknown specs {spec}")

    if bindings:
        vars.maps.insert(0, bindings)
    return "".join(res)


def py_from_file(filename: str | pathlib.Path) -> str:
    "Returns the Python code corresponding to the named file"
    return py_from_text(pathlib.Path(filename).read_text())


def py_from_text(text: str) -> str:
    "Returns the Python code corresponding to text containing queries"
    res: list[str] = []

    res.extend(
        """\

# This code was generated by apsw.query from ::TODO:: fill this in
# and also use $SOURCE_DATE_EPOCH for reproducible build

# do not evaluate annotations at import time (default in Python 3.14+)
from __future__ import annotations

import sys
import apsw
from apsw.query import _ChainMapRO, NotSet, NotSetType, template_expand

""".splitlines()
    )

    for block, value, comments, body in _sections(text):
        match block:
            case "python":
                res.append(f"# {value}")
                res.extend(f"# {line}" for line in comments.splitlines())
                res.append("")
                res.extend(body.splitlines())
                res.append("")
                res.append("")
            case "name":
                # ::TODO:: if body is a template then validate all the
                # spec and conversions

                meta = _parse_name(value)
                res.append(f"class {meta['name']}:")
                if comments.strip():
                    res.extend(_triple_quote(comments, "    "))
                    res.append("")

                # this is going to need an overload or similar to handle async connection
                signature = "(cls, db: apsw.Connection"
                if meta["args"]:
                    signature += ", *"
                    for name, details in meta["args"].items():
                        signature += f", {name}"
                        match (details["annotation"], details["default"]):
                            case (None, _):
                                signature += f" = {details['default']}"
                            case (_, None):
                                signature += f": ({details['annotation']}) | NotSetType = NotSet"
                            case (None, None):
                                signature += "apsw.SQLiteValue | NotSetType = NotSet"
                            case _:
                                signature += f"({details['annotation']}) = {details['default']}"
                signature += ") -> "
                signature += "apsw.Cursor" if meta["return_type"] is None else meta["return_type"]
                res.append("    @classmethod")
                res.append(f"    def __call__{signature}:")
                res.append("        vals = _ChainMapRO()")
                if meta["args"]:
                    res.append("        vals._maps.append({")
                    for name in meta["args"]:
                        res.append(f'            "{name}": {name},')
                    res.append("        })")
                res.extend(
                    """\
        vals.maps.append(sys._getframe(1).f_locals)
        if db.is_async: # use copy as at call time
            vals.maps[1] = vals.maps[-1].copy()
""".splitlines()
                )
                if _is_template_string(body):
                    res.append("        sql = template_expand(")
                    res.extend(_triple_quote(body))
                    res.append("              , vals)")
                else:
                    res.append("        sql = \\")
                    res.extend(_triple_quote(body))
                    res.append("")

                if meta["return_type"] is None:
                    res.append("        return db.execute(sql, vals)")
                else:
                    # ::TODO::
                    pass

                res.append("")
                res.append(f"{meta['name']} = {meta['name']}()")

                res.append("")
                res.append("")
            case _:
                raise ValueError(f"Unknown section {block}")

    return "\n".join(res) + "\n"


def _triple_quote(text: str, indent: str = "") -> list[str]:
    res = []
    triple = '"""'
    text = [line.replace(triple, '"""') for line in text.splitlines()]
    for i, line in enumerate(text):
        res.append(f"{indent}{triple if i == 0 else ''}{line}{triple if i == len(text) - 1 else ''}")
    return res


def _parse_name(text: str):
    res = {}
    # we use ast to do all the work by pretending it is a function
    # definition.  It may not have any parameters listed, so add empty.
    try:
        ast.parse(f"def {text}: pass")
    except SyntaxError:
        # probably record this in res
        text += "()"

    parsed = ast.parse(f"def {text}: pass")
    fn = parsed.body[0]
    res["name"] = fn.name
    res["args"] = {}
    for a, default in zip(fn.args.args, [None] * (len(fn.args.args) - len(fn.args.defaults)) + fn.args.defaults):
        assert a.arg not in res["args"]
        res["args"][a.arg] = {
            "annotation": ast.unparse(a.annotation) if a.annotation else None,
            "default": ast.unparse(default) if default else None,
        }

    res["return_type"] = ast.unparse(fn.returns) if fn.returns else None
    return res


def _sections(text: str):
    title = None
    comments: list[str] = []
    body: list[str] = []

    def part():
        nonlocal title, comments, body
        if title:
            # remove /* and */ from python body
            if title[0] == "python":
                body = [line for line in body if line.strip() not in {"/*", "*/"}]

            # remove leading and trailing blank lines from comments
            # and body
            for lines in comments, body:
                while lines and not lines[0].strip():
                    del lines[0]
                while lines and not lines[-1].strip():
                    del lines[-1]

            yield title[0], title[1], textwrap.dedent("\n".join(comments) + "\n"), "\n".join(body) + "\n"
        title = None
        comments = []
        body = []

    for line in text.splitlines():
        # handle blanks
        if not line.strip():
            # no section yet
            if not title:
                continue
            # body hasn't started
            if not body:
                comments.append(line)
                continue
        mo = re.match(r"^--\s*(?P<type>\w+)\s*:\s*(?P<value>.*?)\s*$", line)
        if mo:
            yield from part()
            title = mo.group("type"), mo.group("value")
            continue
        if not body and line.startswith("--"):
            comments.append(line[2:])
            continue
        body.append(line)
    yield from part()


if __name__ == "__main__":
    import argparse
    import sys

    parser = argparse.ArgumentParser(description="Outputs the Python for a query source")

    parser.add_argument("-o", "--output", help="Output filename [stdout]")

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--file", help="Source is filename")
    group.add_argument(
        "--import",
        metavar="MODULENAME",
        help="Source is a .sql file corresponding to named module.  ie there is a .sql file where normally there would be a .py file",
    )
    group.add_argument(
        "--resource",
        metavar=("MODULENAME", "FILENAME"),
        nargs=2,
        help="Uses importlib.resources given the module name and the filename relative to the module",
    )

    options = parser.parse_args()

    def output():
        if options.output:
            return open(options.output, "wt")
        else:
            return sys.stdout

    if options.file:
        res = py_from_file(options.file)
        o = output()
        try:
            o.write(res)
        finally:
            o.close()
    else:
        sys.exit("not implemented yet")
