name: pyodide TEST pypi

on: workflow_dispatch

jobs:

  pyodide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build pyodide wheel
        uses: pypa/cibuildwheel@v4.1
        env:
          CIBW_BEFORE_BUILD: python -c "import shutil ; shutil.copyfile('tools/setup-pypi.cfg','setup.apsw')"
          CIBW_TEST_COMMAND: python -m apsw.tests -v
          APSW_HEAVY_DURATION: 2
          CIBW_PLATFORM: pyodide
      - uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.os }}-${{ matrix.pyver }}
          path: ./wheelhouse/*.whl

  pypi_publish:
    if: false
    needs: [pyodide]
    runs-on: ubuntu-latest
    permissions:
        id-token: write

    steps:
    - name: Stage wheels
      uses: actions/download-artifact@v8
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip-existing: true
